#!/usr/bin/env bash
# Bash script that stops 4-to_infinity_and_beyond process

# Check if the process is running
if pgrep -f "4-to_infinity_and_beyond" > /dev/null; then
    # Get the process ID
    val=$(pgrep -f "4-to_infinity_and_beyond")

    # Kill the process
    kill "$val"
    echo "Process stopped successfully."
else
    echo "Process is not running."
fi
