#!/usr/bin/env bash
# This script
file_name="7-highlander"
pids=$(pgrep -f "$file_name")
if [ -n "$pids" ]; then
  kill -9 "$pids"
  echo "Processes with file name '$file_name' terminated forcefully."
else
  echo "No processes with file name '$file_name' are currently running."
fi
