#!/usr/bin/env bash
# Change your home IP

# Add entry for facebook.com
echo "8.8.8.8	facebook.com" | sudo tee -a /etc/hosts

# Add entry for localhost
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
